import { IAvailableGenre } from '../../../shared/models/genre.model';

export const myFavouriteGenresContent: IAvailableGenre[] = [
  { name: 'drama' },
  { name: 'comedy' },
  { name: 'death' },
  { name: 'war' },
  { name: 'love' },
  { name: 'animals' },
  { name: 'history' },
  { name: 'fantasy' },
  { name: 'classics' },
  { name: 'fiction' },
  { name: 'children' },
  { name: 'adventure' },
  { name: 'biography' },
  { name: 'romance' },
  { name: 'science' },
  { name: 'christianity' },
  { name: 'france', type: 'place' },
  { name: 'jesus_christ', type: 'person' },
  { name: 'united_states', type: 'place' },
  { name: 'ukraine', type: 'place' },
  { name: 'sex' },
  { name: 'napoleon', type: 'person' },
  { name: 'greece', type: 'place' },
  { name: 'hate' },
  { name: 'magic' },
  { name: 'vampiers' },
  { name: 'poland', type: 'place' },
  { name: 'catholic' },
  { name: 'orthodox' },
  { name: 'young' },
  { name: 'school' },
  { name: 'mother' },
  { name: 'bestseller' },
  { name: 'cars' },
  { name: 'family' },
];
